# Generated by Django 4.2.11 on 2025-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification',
            field=models.FileField(blank=True, null=True, upload_to='notifications/'),
        ),
    ]
