# Generated by Django 4.2.11 on 2025-06-10 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chipin', '0006_event_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='total_spend',
        ),
    ]
