# Generated by Django 4.2.11 on 2025-05-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.FileField(default='pfps/blank.jpg', upload_to=''),
        ),
    ]
